const express = require("express");
const router = express.Router();
const { Spot, User, Booking } = require("../../db/models");

const { requireAuth } = require("../../utils/auth");
const Sequelize = require("sequelize");
const { check } = require("express-validator");
const { handleValidationErrors } = require("../../utils/validation");
const {
  userAttributes,
  reviewImageAttributes,
} = require("../../utils/attributes");

// const errorMessage = {
//   message: "Bad Request", // (or "Validation error" if generated by Sequelize),
//   errors: {
//     address: "Street address is required",
//     city: "City is required",
//     state: "State is required",
//     country: "Country is required",
//     lat: "Latitude must be within -90 and 90",
//     lng: "Longitude must be within -180 and 180",
//     name: "Name must be less than 50 characters",
//     description: "Description is required",
//     price: "Price per day must be a positive number",
//   },
// };

/*
  Quick note:
    I modified the routes we discussed. I made some note of changes. The overall change you should see is that the spots routes are laid out in a way that streamlines the code. Express isn't strict with layout, therefore it can be very hard to keep track of where routes are. I did it to where you start with getting all spots then by then end there's a route to delete a spot. This is my typical layout:

    GET all spots
    GET a single spot
    POST a new spot
    PUT a new spot
    DELETE a spot

    Everything else goes in between.
*/
const validateBooking = [
  check("SpotId")
    .exists({ checkFalsy: true })
    .withMessage("Bad request"), // 400
  check("city").exists({ checkFalsy: true }).withMessage("City is required"), // 400
  check("state").exists({ checkFalsy: true }).withMessage("State is required"), // 400
  check("country")
    .exists({ checkFalsy: true })
    .withMessage("Country is required"), // 400
  check("lat")
    .exists({ checkFalsy: true })
    .isDecimal({ min: -90, max: 90 })
    .withMessage("Latitude must be within -90 and 90"),
  check("lng")
    .exists({ checkFalsy: true })
    .isDecimal({ min: -180, max: 180 })
    .withMessage("Longitude must be within -180 and 180"),
  check("name")
    .exists({ checkFalsy: true })
    .isLength({ max: 50 })
    .withMessage("Name must be less than 50 characters"),
  check("description")
    .exists({ checkFalsy: true })
    .withMessage("Description is required"),
  check("price")
    .exists({ checkFalsy: true })
    .isDecimal({ min: 0 })
    .withMessage("Price per day must be a positive number"),
  handleValidationErrors,
];
const validateSpot = [
  check("address")
    .exists({ checkFalsy: true })
    .withMessage("Street address is required"), // 400
  check("city").exists({ checkFalsy: true }).withMessage("City is required"), // 400
  check("state").exists({ checkFalsy: true }).withMessage("State is required"), // 400
  check("country")
    .exists({ checkFalsy: true })
    .withMessage("Country is required"), // 400
  check("lat")
    .exists({ checkFalsy: true })
    .isDecimal({ min: -90, max: 90 })
    .withMessage("Latitude must be within -90 and 90"),
  check("lng")
    .exists({ checkFalsy: true })
    .isDecimal({ min: -180, max: 180 })
    .withMessage("Longitude must be within -180 and 180"),
  check("name")
    .exists({ checkFalsy: true })
    .isLength({ max: 50 })
    .withMessage("Name must be less than 50 characters"),
  check("description")
    .exists({ checkFalsy: true })
    .withMessage("Description is required"),
  check("price")
    .exists({ checkFalsy: true })
    .isDecimal({ min: 0 })
    .withMessage("Price per day must be a positive number"),
  handleValidationErrors,
];

// get all spots
router.get("/", async (req, res) => {
  try {
    const allSpots = await Spot.findAll();
    res.json(allSpots);
  } catch (e) {
    console.error(e);
    res.status(500).send("Internal Server Error");
  }
});

// get all spots by owner id
router.get("/:ownerId", requireAuth, async (req, res, next) => {
  const ownerId = Number(req.params.ownerId);
  try {
    const allSpots = await Spot.findAll({
      where: { ownerId },
    });

    res.json(allSpots);
  } catch (e) {
    res.status(500);
    console.error(e);
    next(e);
  }
});

//get spot by spot id
// I went back through the routes I don't see any conflicting routes?
// I can see how this got you confused on the routing
// You're still gonna use /api/spots/:spotId
router.get("/:spotId", async (req, res, next) => {
  const spotId = Number(req.params.spotId);

  try {
    // const spot = await Spot.findOne({
    //   where: { id: spotId },
    //   include: [
    //     {
    //       model: User,
    //       where: { id: Sequelize.col("Spot.ownerId") }, // Match User's id to Spot's ownerId
    //       attributes: ["id", "firstName", "lastName"],
    //       as: "Owner",
    //     },
    //   ],
    // });

    // Here's a quick way you could write this
    const spot = await Spot.findByPk(spotId, {
      include: [
        {
          model: User,
          attributes: userAttributes, // only has id, firstName, lastName
          as: "Owner",
        },
        {
          model: Image,
          attributes: imageAttributes,
          as: "SpotImages",
        },
      ],
    });
    if (!spot) {
      //spot not found
      return res.status(404).json({ message: "Spot couldn't be found" });
    }

    res.json(spot);
  } catch (e) {
    res.status(500);
    console.error(e);
    next(e);
  }
});

// create a spot
router.post("/", requireAuth, validateSpot, async (req, res) => {
  const ownerId = req.user.id;
  const { address, city, state, country, lat, lng, name, description, price } =
    req.body;
  try {
    const spot = await Spot.create({
      ownerId,
      address,
      city,
      state,
      country,
      lat,
      lng,
      name,
      description,
      price,
    });
    if (!spot) {
      return res.status(400).json(errorMessage);
    }
    res.status(201).json(spot);
  } catch (e) {
    console.error(e);
    res.status(500).send("Internal Server Error");
  }
});

// Add image to spot based on spot id
router.post("/:spotId/images", requireAuth, async (req, res) => {
  const ownerId = req.user.id;
  const { url, preview } = req.body;
  const spotId = Number(req.params.spotId);
  try {
    const spot = await Spot.findByPk(spotId);

    if (!spot) {
      const err = new Error("Spot couldn't be found");
      err.status = 404;
      next(err);
    }
    if (spot.ownerId !== ownerId) {
      const err = new Error("Forbidden");
      err.status = 403;
      next(err);
    }
    const newImage = await spot.createImage({
      url,
      preview,
    });
    res.status(201).json(newImage);
  } catch (e) {
    e.status = 500;
    next(e);
  }
});
// create booking from spot id
router.post("/:spotId/bookings", requireAuth, async (req, res, next) => {
  const userId = req.user.id;
  const { startDate, endDate } = req.body;
  const spotId = Number(req.params.spotId);

  try {

    const booking = await Booking.create({spotId,userId,startDate,endDate})
    const spot = await Spot.findByPk(spotId)
    if(userId === spot.OwnerId){
      throw new Error('Spot must not belong to user')
    }
    if (!spot) {
      const err = new Error("Spot couldn't be found");
      err.status = 404;
      next(err);
    }
  ;
// need help with .check for body validation errors
    res.status(201).json(booking);
  } catch (e) {
    e.status = 500;
    next(e);
  }
});

// edit a spot by spot id
router.put("/:spotId", requireAuth, validateSpot, async (req, res) => {
  const ownerId = req.user.id;
  const { address, city, state, country, lat, lng, name, description, price } =
    req.body;

  const spotId = Number(req.params.spotId);

  try {
    const spot = await Spot.findByPk(spotId);

    if (!spot) {
      const err = new Error("Spot couldn't be found");
      err.status = 404;
      next(err);
    }

    await spot.update({
      ownerId,
      address,
      city,
      state,
      country,
      lat,
      lng,
      name,
      description,
      price,
    });
    await spot.save();
    res.status(200).json({ spot });
  } catch (e) {
    e.status = 500;
    next(e);
  }
});

// delete spot by spot id
router.delete("/:spotId", requireAuth, async (req, res) => {
  const spotId = Number(req.params.spotId);

  try {
    const spot = await Spot.findByPk(spotId);
    if (!spot) {
      const err = new Error("Spot couldn't be found");
      err.status = 404;
      return next(err);
    }
    if (spot.ownerId !== req.user.id) {
      const err = new Error("Forbidden");
      err.status = 403;
      return next(err);
    }
    spot.destroy();
    res.json({ message: "Successfully deleted" });
  } catch (e) {
    e.status = 500;
    next(e);
  }
});


// create booking from spot id
module.exports = router;
